In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[ 0.78397551 -1.19255027 -2.47478686 -0.94598394 -1.05703794]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.78397551 -1.19255027 -2.47478686 -0.94598394 -1.05703794]


In [5]:
print(np.dot(a, a.T))

10.173578586037763


In [6]:
a = np.random.randn(5,1)
print(a)

[[ 0.57995768]
 [ 0.78624104]
 [-0.08348863]
 [ 0.53586956]
 [ 1.17800619]]


In [7]:
print(a.T)

[[ 0.57995768  0.78624104 -0.08348863  0.53586956  1.17800619]]


In [8]:
print(np.dot(a, a.T))

[[ 0.33635091  0.45598653 -0.04841987  0.31078167  0.68319374]
 [ 0.45598653  0.61817498 -0.06564219  0.42132264  0.92619682]
 [-0.04841987 -0.06564219  0.00697035 -0.04473902 -0.09835013]
 [ 0.31078167  0.42132264 -0.04473902  0.28715619  0.63125766]
 [ 0.68319374  0.92619682 -0.09835013  0.63125766  1.38769859]]
